apiVersion: apps/v1
kind: Deployment
metadata:
    name: devopscourseproject
spec:
    selector:
        matchLabels:
            app: DevOps-Course-Project
    replicas: 3
    template:
        metadata:
            labels:
                app: DevOps-Course-Project
        spec:
            containers:
                - name: devopscourseproject-api
                  image: ${{ secrets.DOCKERHUB_USERNAME }}/devopscourseproject:latest
                  ports:
                      - containerPort: 5000
