apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopscourseproject-deployment
spec:
  selector:
    matchLabels:
      app: devopscourseproject
  replicas: 3
  template:
    metadata:
      labels:
        app: devopscourseproject
    spec:
      containers:
      - name: devopscourseproject-container
        image: ${{ secrets.DOCKERHUB_USERNAME }}/devopscourseproject:latest
        ports:
        - containerPort: 5000
