apiVersion: apps/v1
kind: Deployment
metadata:
    name: devopscourseprojectnode
spec:
    selector:
        matchLabels:
            app: devopscourseproject
    replicas: 3
    template:
        metadata:
            labels:
                app: devopscourseproject
        spec:
            containers:
                - name: devopscourseproject
                  image: iliyan31/devopscourseproject:latest
                  ports:
                      - containerPort: 5000
