apiVersion: v1
kind: Service
metadata:
    name: devopscourseprojectnode
spec:
    type: NodePort
    selector:
        app: devopscourseproject-api
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
