apiVersion: v1
kind: Service
metadata:
    name: devopscourseprojectnode
spec:
    type: NodePort
    selector:
        app: devopscourseprojecte-api
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
