name: DevOps Course Project main workflow
on:
  push:
    branches: 
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  Build-And-Publish-Docker-Image:
    name: Publish the docker image
    runs-on: ubuntu-latest
    needs: Trivy-Scan-And-Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t devopscourseproject ./src

      - name: Add tag to docker image
        run: docker tag devopscourseproject ${{ secrets.DOCKERHUB_USERNAME }}/devopscourseproject

      - name: Publish to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devopscourseproject
