name: DevOps Course Project main workflow
on:
  push:
    branches: 
      - '**'

jobs:
  # Sonarcloud-Code-Scan:
  #   name: SonarCloud scan
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # SpectralOps-Vulnerability-Scan:
  #   name: Spectral ubuntu CI
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
      
  #     - name: Install and run Spectral CI
  #       uses: spectralops/spectral-github-action@v4
  #       with:
  #         spectral-dsn: ${{ secrets.SPECTRAL_DSN }}
  #         spectral-args: scan --ok

  Bandit-SAST-Checker:
    name: Bandit Vulnerability Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Bandit Report
        uses: libertyy/py3-bandit-check@v2
        
      - name: Save Bandit txt Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          path: ${{ RUNNER.temp }}/_github_home/bandit_report.out 